### ISSUE TITLE
Yarn dev returns errors on fresh clone

### ISSUE THREAD

**Issue by tomaszzmudzinski** [n6g7/httpdf#305]
Hi,

I cloned your project, did 'yarn install' and then 'yarn dev' and I am getting errors like this:

Error: Cannot find module './../.build/asyncProps.js'
Error: Cannot find module './../.build/broken.js'
Error: Cannot find module './../.build/demo.js'
Error: Cannot find module './../.build/components/index.js'

Could you help me to fix this problem and make it work?

**Comment by n6g7** [comment]
Hey, sorry for the very late reply. This should be fixed with the switch to esm from today.
Feel free to re-open if you're still having issues (and still care about this issue 😅).
