### ISSUE TITLE
Change the value of AuthnCacheContext?

### ISSUE THREAD

**Issue by HCHCHH** [n6g7/httpdf#45]
Thanks for providing the container! I have a question about one httpd config:`AuthnCacheContext`.
It seems the [official document](https://httpd.apache.org/docs/current/mod/mod_authn_socache.html#authncachecontext) recommends to change the default `directory`, which is conservative and not optimal. **A better policy is to name the `AuthnCacheContext` for the password provider: for example a htpasswd file or database table.**

Maybe it's better to set that to specify a context string for use in the cache keyin the comfig file? Thanks.

**Comment by n6g7** [comment]
Hi @HCHCHH, I think there's a misunderstanding here, this project has nothing to do with httpd or Apache, it is a docker container to generate pdf files via http.
You should bring this up on the [httpd project](https://github.com/apache/httpd) instead. :)

Sorry for the confusion, I hadn't realised that this project name was one letter away from httpd. 😅
